#define submenu1                              	"录像检索"
#define submenu2                              	"录像设置"
#define submenu3                              	"功能设置"
#define submenu4                              	"系统信息"
#define submenu5                              	"车辆管理"
#define submenu6                              	"显示设置"
#define submenu7                              	"密码管理"
#define submenu8                              	"退   出"
#define capture        "                                                      主窗口"
